### ISSUE TITLE
MAX32570Q Dual Mode

### ISSUE THREAD

**Issue by kevin-gillespie** [Analog-Devices-MSDK/openocd#4]
Dual mode doesn't work on the MAX32570Q EvKit.

**Comment by kevin-gillespie** [comment]
We could be violating this spec. The default setting for the SS inactive is 1 system clock ~6.7 ns on the ME13. Not sure why this would work in single mode an fail in dual mode. 

![CS_deselect_time](https://user-images.githubusercontent.com/54692400/184960587-a9c76690-af81-4dde-9192-9e0eee10973c.PNG)

**Comment by kevin-gillespie** [comment]
I maxed out the SS timing parameters and that didn't help. Still fails with dual mode encrypted authenticated.

**Comment by kevin-gillespie** [comment]
@bob1033  We might have to look closer at the SS active/inactive settings. It seems like these are not having any effect for the authenticated data fetches. I'm measuring the SS inactive time on an oscilloscope and it looks like changing the settings for the SPIXFM don't affect the de-assert time.

**Comment by kevin-gillespie** [comment]
@kevin-gillespie 

TODO: Reset the SPI settings when making changes.

**Comment by bob1033** [comment]
When re-configuring the SPIXIP block, it is also recommended to disable and invalidate the cache.
We will want to use a sequence like below every time we want to reconfigure the block:
```
MXC_SFCC->ctrl = ((uint32_t)0x00000000UL);        // Disable iCache_XIP
MXC_GCR->rst1 |= MXC_F_GCR_RST1_SPIXIP;          // Reset XIP
while (MXC_GCR->rst1 != 0x00);                   // Wait on Reset XIP
MXC_SFCC->invalidate = 1;                         // Invalidate iCache_XIP
while(!(MXC_SFCC->ctrl & MXC_F_ICC_CTRL_RDY));
```
